kind: GatewayClass
apiVersion: networking.x.k8s.io/v1alpha1
metadata:
  name: acme-lb
controller: acme.io/gateway-controller
parameters:
  apiGroup: networking.acme.io
  kind: AcmeLBConfig
  name: acme-lb-config
---
kind: Gateway
apiVersion: networking.x.k8s.io/v1alpha1
metadata:
  name: my-gateway
  namespace: default
spec:
  class: acme-lb
  listeners:  # Use GatewayClass defaults for listener definition.
  - name: my-tcp-listener
    protocol: TCP
  routes:
    namespaceSelector:
      matchLabels:
        "": ""
---
kind: TcpRoute
apiVersion: networking.x.k8s.io/v1alpha1
metadata:
  name: tcp-app-1
  namespace: default
spec:
  hosts:
  - rules:
    - match:
        listener: my-tcp-listener
      action:
        forwardTo:
          resource: Service
          group: core
          name: my-service
